name: Publish Docker aerepl image

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      - name: Build and push
        id: gen_tags
        run: |
          if [[ $GITHUB_REF == 'refs/tags/'* ]]; then
            TAGS='["aeturnity/test:latest","aeturnity/test:'${GITHUB_REF/refs\/tags\//}'"]'
          else
            TAGS='["aeturnity/test:master"]'
          fi
          echo '::set-output name=tags::'$TAGS

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        needs: gen_tags
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ fromJson(steps.gen_tags.outputs.tags) }}
